name: adsb-box
version: '0.3'
summary: ADS-B tools
description: |
  This snap includes several ADS-B related tools to let users builds their
  own ADS-B receiver station. There are dump1090 and lighttpd in this snap.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  dump1090:
    command: bin/dump1090
    daemon: simple
    plugs: [network, network-bind, raw-usb, process-control]
  lighttpd:
    command: bin/lighttpd
    daemon: simple
    plugs: [network, network-bind]
  piaware:
    command: bin/piaware
    daemon: simple
    plugs: [network,network-bind,system-observe,network-observe,mount-observe,hardware-observe]
  piaware-config:
    command: bin/piaware-config
  piaware-status:
    command: bin/piaware-status
    plugs: [network,system-observe,network-observe]
 
parts:
  common:
    plugin: dump
    source: .
    prime:
      - bin/dump1090
      - bin/lighttpd
      - bin/piaware
      - bin/piaware-config
      - bin/piaware-status

  dump1090:
    plugin: make
    make-parameters: ['dump1090', 'faup1090']
    source: https://github.com/mutability/dump1090.git
    source-type: git
    #source-branch: v1.14
    prepare: |
        echo 'patching dump1090 ...'
        patch -p1 < ../../../patches/dump1090.patch
        cp ../../../patches/dump1090/Taiwan.png public_html/flags-tiny/
    artifacts:
      - dump1090
      - faup1090
      - public_html
      - debian/config-template
      - COPYING
    organize:
      dump1090: usr/bin/dump1090-mutability
      faup1090: usr/lib/piaware/helpers/faup1090
      public_html: usr/share/dump1090-mutability/html
      debian: etc
      etc/config-template: usr/share/dump1090-mutability/config-template
      COPYING: usr/share/dump1090-mutability/COPYING
    build-packages:
      - pkg-config
      - libusb-1.0-0-dev
      - librtlsdr-dev

  lighttpd:
    plugin: nil
    stage-packages:
      - lighttpd
    prime:
      - usr/sbin/lighttpd
      - usr/lib/libfam*
      - usr/lib/lighttpd/mod_access.so
      - usr/lib/lighttpd/mod_alias.so
      - usr/lib/lighttpd/mod_compress.so
      - usr/lib/lighttpd/mod_redirect.so
      - usr/lib/lighttpd/mod_indexfile.so
      - usr/lib/lighttpd/mod_dirlisting.so
      - usr/lib/lighttpd/mod_staticfile.so
      - usr/share/doc/lighttpd/copyright

  tcllauncher:
    plugin: autotools
    source: https://github.com/flightaware/tcllauncher.git
    source-type: git
    prepare: |
      echo 'patching tcllauncher ...'
      patch -p1 < ../../../patches/tcllauncher.patch
    configflags: ['--with-tcl=/usr/lib/tcl8.6']
    build-packages:
      - tcl8.6-dev

  piaware:
    after: [tcllauncher]
    plugin: make
    source: https://github.com/flightaware/piaware.git
    source-type: git
    source-branch: v3.5.0
    prepare: |
      echo 'patching piaware ...'
      patch -p1 < ../../../patches/piaware.patch
    stage-packages:
      - tclx8.4
      - tcl8.6
      - tcllib
      - tcl-tls
      - itcl3
    stage:
      # these pkgIndex.tcl files will be processed at 'pkgindex-patch' parts
      - -usr/lib/tcltk/x86_64-linux-gnu/itcl3.4/pkgIndex.tcl
      - -usr/lib/tcltk/i386-linux-gnu/itcl3.4/pkgIndex.tcl
      - -usr/lib/tcltk/arm-linux-gnueabihf/itcl3.4/pkgIndex.tcl
      - -usr/lib/tcltk/aarch64-linux-gnu/itcl3.4/pkgIndex.tcl
      - -usr/lib/tclx8.4/pkgIndex.tcl
      - -usr/share/tcltk/tls1.6.7/pkgIndex.tcl
    prime:
      - -usr/share/doc
      - -usr/share/man

  mlat-client:
    plugin: python
    source: https://github.com/mutability/mlat-client.git
    source-type: git
    organize:
      bin/fa-mlat-client: usr/lib/piaware/helpers/fa-mlat-client
    prime:
      - -usr/share/doc
      - -usr/share/man

  pkgindex-patch:
    plugin: nil
    after: [piaware]
    build: |
        echo "copy and patch pkgindex files"
        cp ../../piaware/install/usr/lib/tcltk/*/itcl3.4/pkgIndex.tcl itcl3.4-pkgIndex.tcl
        cp ../../piaware/install/usr/lib/tclx8.4/pkgIndex.tcl tclx8.4-pkgIndex.tcl
        cp ../../piaware/install/usr/share/tcltk/tls1.6.7/pkgIndex.tcl tls1.6.7-pkgIndex.tcl
        sed -i 's/\/usr/\$\:\:env\(SNAP\)\/usr/g' *-pkgIndex.tcl
    install: |
        echo "install patched pkgindex files"
        ARCHDIR=`ls ../../piaware/install/usr/lib/tcltk`
        echo "ARCHDIR=$ARCHDIR"
        mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/tcltk/$ARCHDIR/itcl3.4/
        cp itcl3.4-pkgIndex.tcl $SNAPCRAFT_PART_INSTALL/usr/lib/tcltk/$ARCHDIR/itcl3.4/pkgIndex.tcl
        mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/tclx8.4
        cp tclx8.4-pkgIndex.tcl $SNAPCRAFT_PART_INSTALL/usr/lib/tclx8.4/pkgIndex.tcl
        mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/tcltk/tls1.6.7/
        cp tls1.6.7-pkgIndex.tcl $SNAPCRAFT_PART_INSTALL/usr/share/tcltk/tls1.6.7/pkgIndex.tcl

