name: adsb-box
version: '0.7'
summary: ADS-B tools
description: |
  This snap includes several ADS-B related tools to let users builds their
  own ADS-B receiver station. There are dump1090 and lighttpd in this snap.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  dump1090:
    command: bin/dump1090
    daemon: simple
    plugs: [network, network-bind, raw-usb, process-control]
  lighttpd:
    command: bin/lighttpd
    daemon: simple
    plugs: [network, network-bind]
  piaware:
    command: bin/piaware
    daemon: simple
    plugs: [network, network-bind, system-observe, network-observe, mount-observe, hardware-observe]
  piaware-config:
    command: bin/piaware-config
  piaware-status:
    command: bin/piaware-status
    plugs: [network, system-observe, network-observe]
  fr24feed:
    command: bin/fr24feed
    daemon: simple
    plugs: [network, network-bind, network-observe]
  fr24feedcli:
    command: bin/fr24feed
    plugs: [network, network-bind, network-observe]
  rtltest:
    command: usr/bin/rtl_test
    plugs: [network, network-bind, raw-usb]
  collectd:
    command: bin/collectd
    daemon: simple
    plugs: [network, system-observe, network-observe, mount-observe, hardware-observe]
  graphs-gend:
    command: bin/graphs-gend
    daemon: simple
    plugs: [process-control]

parts:
  common:
    plugin: dump
    source: .
    organize:
      www: var/www
    prime:
      - bin
      - etc
      - var

  dump1090:
    plugin: make
    make-parameters: ['dump1090', 'faup1090']
    source: https://github.com/mutability/dump1090.git
    source-type: git
    #source-branch: v1.14
    override-build: |
      echo 'patching dump1090 ...'
      patch -p1 < ../../../patches/dump1090.patch
      cp ../../../patches/dump1090/Taiwan.png public_html/flags-tiny/
      snapcraftctl build
    artifacts:
      - dump1090
      - faup1090
      - public_html
      - debian/config-template
      - COPYING
    organize:
      dump1090: usr/bin/dump1090-mutability
      faup1090: usr/lib/piaware/helpers/faup1090
      public_html: usr/share/dump1090-mutability/html
      debian: etc
      etc/config-template: usr/share/dump1090-mutability/config-template
      COPYING: usr/share/dump1090-mutability/COPYING
    build-packages:
      - pkg-config
      - libusb-1.0-0-dev
      - librtlsdr-dev

  lighttpd:
    plugin: nil
    stage-packages:
      - lighttpd
    prime:
      - usr/sbin/lighttpd
      - usr/lib/libfam*
      - usr/lib/lighttpd
      - usr/share/doc/lighttpd/copyright

  tcllauncher:
    plugin: autotools
    source: https://github.com/flightaware/tcllauncher.git
    source-type: git
    override-build: |
      echo 'patching tcllauncher ...'
      patch -p1 < ../../../patches/tcllauncher.patch
      snapcraftctl build
    configflags: ['--with-tcl=/usr/lib/tcl8.6']
    build-packages:
      - tcl8.6-dev

  piaware:
    after: [tcllauncher]
    plugin: make
    source: https://github.com/flightaware/piaware.git
    source-type: git
    source-branch: v3.6.3
    override-build: |
      echo 'patching piaware ...'
      patch -p1 < ../../../patches/piaware.patch
      snapcraftctl build
      echo 'patching pkgIndex.tcl files ...'
      sed -i 's/\/usr/\$\:\:env\(SNAP\)\/usr/g' \
        $SNAPCRAFT_PART_INSTALL/usr/lib/tcltk/$SNAPCRAFT_ARCH_TRIPLET/itcl3.4/pkgIndex.tcl \
        $SNAPCRAFT_PART_INSTALL/usr/lib/tclx8.4/pkgIndex.tcl \
        $SNAPCRAFT_PART_INSTALL/usr/share/tcltk/tls1.6.7/pkgIndex.tcl \
        || \
        exit 1
    stage-packages:
      - tclx8.4
      - tcl8.6
      - tcllib
      - tcl-tls
      - itcl3
    prime:
      - -usr/share/doc
      - -usr/share/man

  mlat-client:
    plugin: python
    source: https://github.com/mutability/mlat-client.git
    source-type: git
    override-build: |
      echo 'Replacing distutils with setuptools ...'
      sed -i 's/distutils\.core/setuptools/g' setup.py
      echo 'Building mlat-client ...'
      snapcraftctl build
    organize:
      bin/fa-mlat-client: usr/lib/piaware/helpers/fa-mlat-client
    prime:
      - -usr/share/doc
      - -usr/share/man

  fr24feed:
    plugin: nil
    build-packages:
      - wget
    override-pull: |
      env | sort
      snapcraftctl pull
      case $SNAPCRAFT_ARCH_TRIPLET in
        x86_64-*)
          wget -O fr24feed.tgz https://repo-feed.flightradar24.com/linux_x86_64_binaries/fr24feed_1.0.18-5_amd64.tgz
          ;;
        i386-*)
          wget -O fr24feed.tgz https://repo-feed.flightradar24.com/linux_x86_binaries/fr24feed_1.0.18-5_i386.tgz
          ;;
        arm-*|aarch64-*)
          wget -O fr24feed.tgz https://repo-feed.flightradar24.com/rpi_binaries/fr24feed_1.0.23-8_armhf.tgz
          ;;
        *)
          echo "Unknown architecture: $SNAPCRAFT_ARCH_TRIPLET"
          exit 1
          ;;
      esac
    override-build: |
      # build
      tar zxf $SNAPCRAFT_PART_SRC/fr24feed.tgz
      # install
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin $SNAPCRAFT_PART_INSTALL/usr/bin
      cp fr24feed_*/fr24feed $SNAPCRAFT_PART_INSTALL/usr/bin

  rtlsdr:
    plugin: nil
    stage-packages:
      - rtl-sdr

  collectd:
    plugin: nil
    stage-packages:
      - collectd
      - python2.7
      - libpython2.7
    stage:
      - -etc/fonts/fonts.conf

  graphs-gend:
    plugin: nil
    source: https://github.com/jprochazka/adsb-receiver.git
    source-type: git
    stage-packages:
      - rrdtool
    override-build: |
      # patch
      echo 'patching adsb-receiver scripts ...'
      patch -p1 < ../../../patches/graphs-gend.patch
      # no build process is required
      # install
      pwd
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/adsb-receiver
      cp -a build/portal/graphs $SNAPCRAFT_PART_INSTALL/usr/share/adsb-receiver
    stage:
      - -etc/fonts/fonts.conf

passthrough:
  layout:
    /etc/fr24feed.ini:
      bind-file: $SNAP_DATA/fr24feed.ini

